### ISSUE TITLE
Обучить модель

### ISSUE THREAD

**Issue by anyasarybaeva** [anyasarybaeva/Mansi-Legends#11]
Обучить модель и сделать выводы по результатам

**Comment by anyasarybaeva** [comment]
первая итерация готова

**Comment by mizoru** [comment]
Дообученная lightblue/suzume-llama-3-8B-multilingual показывает результаты chrf 42.2, BLEU 14.8%.

**Comment by mizoru** [comment]
![Image](https://github.com/user-attachments/assets/075c5699-fdd1-4949-9c3a-9d2e0afa0f10)
[facebook/nllb-200-distilled-600M](https://huggingface.co/facebook/nllb-200-distilled-600M) с 2935 новыми токенами в словаре обученная на протяжении 56000 шагов дает BLEU 23.24 на русском и 23.16 на мансийском.
![Image](https://github.com/user-attachments/assets/9b20cd55-10e0-45d7-9996-fb767c21a6b2)

**Comment by mizoru** [comment]
![Image](https://github.com/user-attachments/assets/fdc949cc-d75f-4648-b3f1-8bde4df72dd2)

**Comment by mizoru** [comment]
BPE-Dropout не дает стабильного повышения качества
