### ISSUE TITLE
код для инференса 

### ISSUE THREAD

**Issue by anyasarybaeva** [anyasarybaeva/Mansi-Legends#12]

**Comment by mizoru** [comment]
Добавлен код для инференса в [ветвь 12](https://github.com/anyasarybaeva/Mansi-Legends/tree/12).
Чекпоинт модели для тестирования бэка - [тут](https://disk.yandex.ru/d/eSdC5ZuugNbc2g).

Предварительно установить нужную версию transformers - `pip install -r requirements.txt`
Пример использования модели для получения перевода на Мансийский:

```
from inference import load, translate

model, tokenizer = load("/data/msvistunov/m/vocab")
model = model.cuda()

translate("Привет, меня зовут Максим, как дела?", model, tokenizer, to_ru=False)
```
