### ISSUE TITLE
Сделать презу к 1 чекпоинту

### ISSUE THREAD

**Issue by anyasarybaeva** [anyasarybaeva/Mansi-Legends#8]
*MVP v1.0 (демо необязательно на момент первого чекпоинта) - Драфт презы на основе Pitch Deck готов к публикации (дополнительно) используя #7 #6

**Comment by VadimPanenko** [comment]
Презентация к первому чекпоинту в PDF формате
[Mansi-Legends-1-чекпоинт.pdf](https://github.com/user-attachments/files/16984886/Mansi-Legends-1-.pdf)
